apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-bff
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-bff
  template:
    metadata:
      labels:
        app: mobile-bff
    spec:
      containers:
      - name: mobile-bff
        image: joshh99/mobile_bff:latest
        ports:
        - containerPort: 80
        env:
        - name: BOOK_COMMAND_URL
          value: http://book-command-service.bookstore-ns.svc.cluster.local:3000
        - name: BOOK_QUERY_URL
          value: http://book-query-service.bookstore-ns.svc.cluster.local:3000
        - name: CUSTOMER_URL
          value: http://customer-service.bookstore-ns.svc.cluster.local:3000
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10