apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
  namespace: bookstore-ns
type: Opaque
data:
  database-url: bXlzcWw6Ly9hd3NhZG1pbjpXZXNsZW5hOTlAYm9va3N0b3JlLWRiLWRldi1pbnN0YW5jZTIuYzl0YnNvZW8xdnEzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbS9Cb29rU3RvcmU=
  smtp-user: am9zaHVhd2lzZG9tOTJAZ21haWwuY29t
  smtp-password: ZHZwcyByZ2RkIGhyb24gYXl0eg==
  mongo-uri: bW9uZ29kYitzcnY6Ly9qbW9tbzpqbGF1WE93anRHa0IwZFY3QGFzc2lnbm1lbnQ0Lnl2YnczZGEubW9uZ29kYi5uZXQvQm9va3NEQg==