apiVersion: batch/v1
kind: CronJob
metadata:
  name: book-data-sync
  namespace: bookstore-ns
spec:
  schedule: "*/1 * * * *"  # Every 60 seconds
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: book-data-sync
            image: joshh99/data_sync_job:latest
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: database-url
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: mongo-uri
          restartPolicy: OnFailure