apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
  namespace: bookstore-ns
type: Opaque
data:
  database-url: bXlzcWw6Ly9yb290OmdvZGlza2luZ0Bib29rc3RvcmUtZGItZGV2LWluc3RhbmNlMi5jemk0bXUyc2t4Zm0udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjMzMDYvQm9va1N0b3Jl
  smtp-user: ZGQubmFuYW1AZ21haWwuY29t
  smtp-password: cGVxbiBsdHp2IHF5dW4gdXZsZQ==
  mongo-uri: kuyfgku
