apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
      - name: crm-service
        image: ddnanam/crm_service:latest
        env:
        - name: KAFKA_BROKER
          value: 3.129.102.184:9092,18.118.230.221:9093,3.130.6.49:9094
        - name: KAFKA_TOPIC
          value: dnanam.customer.evt
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: joshuawisdom92@gmail.com
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: dvps rgdd hron aytz
        - name: ANDREW_ID
          value: jmomo